In [1]:
import numpy as np

In [4]:
from time import process_time
python_list =[i for i in range(1000000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.15625


In [11]:
np_array = np.array([i for i in range(10000000)])
start_time = process_time()
np_time += 5
end_time= process_time()
print(end_time-start_time)

0.0


In [13]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [15]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [18]:
a.shape

(4,)

In [20]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
b.shape

(2, 4)

In [24]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [27]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
z =np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [32]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
b = np.random.random((3,4))
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [38]:
c = np.random.randint(10,100,(3,5))
print(c)

[[95 36 24 56 92]
 [58 56 30 82 31]
 [20 82 60 64 19]]


In [41]:
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [44]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [46]:
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [49]:
c = np.random.randint(10,90,(5,5))
print(c)

[[83 69 71 42 50]
 [82 61 38 35 74]
 [22 21 83 14 49]
 [76 77 86 26 28]
 [18 87 65 46 21]]


In [51]:
print(c.shape)

(5, 5)


In [53]:
print(c.ndim)

2


In [54]:
print(c.size)

25


In [56]:
print(c.dtype)

int32


In [59]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[9 0 0]
 [3 4 6]
 [1 9 6]]
[[11 11 16]
 [17 17 17]
 [17 15 18]]


In [61]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 11 16]
 [20 21 23]
 [18 24 24]]
[[ -2 -11 -16]
 [-14 -13 -11]
 [-16  -6 -12]]
[[ 99   0   0]
 [ 51  68 102]
 [ 17 135 108]]
[[0.81818182 0.         0.        ]
 [0.17647059 0.23529412 0.35294118]
 [0.05882353 0.6        0.33333333]]


In [63]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 8 7]
 [0 9 0]
 [9 6 9]]
[[17 11 16]
 [19 16 18]
 [17 17 16]]


In [65]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[20 19 23]
 [19 25 18]
 [26 23 25]]
[[-14  -3  -9]
 [-19  -7 -18]
 [ -8 -11  -7]]
[[ 51  88 112]
 [  0 144   0]
 [153 102 144]]
[[0.17647059 0.72727273 0.4375    ]
 [0.         0.5625     0.        ]
 [0.52941176 0.35294118 0.5625    ]]


In [68]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 1 5]
 [6 3 2]]
(2, 3)


In [70]:
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 6]
 [1 3]
 [5 2]]
(3, 2)


In [73]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 2 8]
 [5 5 0]]
(2, 3)


In [75]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 5]
 [2 5]
 [8 0]]
(3, 2)


In [77]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)
b=a.reshape(3,2)
print(b)
print(b.shape)

[[9 6 8]
 [8 9 5]]
(2, 3)
[[9 6]
 [8 8]
 [9 5]]
(3, 2)
